config/routes.rb
Penezotron::Application.routes.draw do
  resources :users, :user_sessions, :transactions
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'conciliation' => 'home#conciliation', :as => :conciliation

  root :to => 'home#default', :as => :home

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	# GET /transactions
	# GET /transactions.json
	def index
		@transactions = Transaction.paginate(:page => params[:page], :per_page => 25).order('created_at DESC')

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @transactions }
		end
	end

	# GET /transactions/1
	# GET /transactions/1.json
	def show
		@transaction = Transaction.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @transaction }
		end
	end

	# GET /transactions/1/edit
	def edit
		@transaction = Transaction.find(params[:id])
	end

	# POST /transactions
	# POST /transactions.json
	def create
		payer = params[:transaction][:payer].to_i
		params[:transaction].delete :payer

		params[:transaction][:amount] = Calc.evaluate(params[:transaction][:amount])

		@transaction = Transaction.new(params[:transaction])
		if payer
			@transaction.payer = payer
		else
			@transaction.payer = current_user.id
		end

		respond_to do |format|
			if @transaction.save
				format.html { redirect_to :home, notice: 'Transaction was successfully created.' }
				format.json { render json: @transaction, status: :created, location: @transaction }
			else
				format.html { redirect_to :home }
				format.json { render json: @transaction.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /transactions/1
	# PUT /transactions/1.json
	def update
		@transaction = Transaction.find(params[:id])

		respond_to do |format|
			if @transaction.update_attributes(params[:transaction])
				format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @transaction.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /transactions/1
	# DELETE /transactions/1.json
	def destroy
		@transaction = Transaction.find(params[:id])
		@transaction.destroy

		respond_to do |format|
			format.html { redirect_to transactions_url }
			format.json { head :no_content }
		end
	end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Uzivatel: <%= current_user.username %>
  </div>

  <div class="field">
	  Pro:
	  <% User.all.each do |user| %>
		  <%= check_box_tag("transaction[user_list][#{user.id}]", "1", @transaction.users.detect{|d| d == user}) %>
		  <%= user.username %>
	  <% end %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :notes %>
    <%= f.text_field :notes %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Seznam transakcí</h1>

<table class="transaction-list table table-striped table-bordered table-hover">
	<thead>
		<tr>
			<th>Věc</th>
			<th>Zaplatil</th>
			<th>Pro</th>
			<th>Kolik</th>
			<th>Vytvořeno</th>
		</tr>
	</thead>

	<tbody>
		<% @transactions.each do |transaction| %>
			<tr>
				<td><%= link_to transaction.name, transaction %></td>
				<td><%= User.find_by_id(transaction.payer).username %></td>
				<td><%= transaction.nice_user_list %></td>
				<td><%= money transaction.amount %></td>
				<td><%= datetime transaction.created_at %></td>
			</tr>
		<% end %>
	</tbody>

	<tfoot>
		<tr>
			<td colspan="5">
				<%= will_paginate @transactions %>
			</td>
		</tr>
	</tfoot>
</table>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Detail transakce</h1>

<b><%= money @transaction.amount %>: <%= @transaction.name %></b><br />
<b>Koupil:</b> <%= User.find_by_id(@transaction.payer).username %><br />
<b>Pro:</b> <%= @transaction.nice_user_list %> <br />
<b>Poznámky:</b> <%= @transaction.notes %>
<b>Vytvořeno:</b> <%= @transaction.created_at %>
<br />

<%= link_to 'Destroy', @transaction, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>