config/routes.rb
Penezotron::Application.routes.draw do
  resources :users, :user_sessions, :transactions
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'conciliation' => 'home#conciliation', :as => :conciliation

  root :to => 'home#default', :as => :home

end

app/models/user_session.rb
# encoding: UTF-8

class UserSession < Authlogic::Session::Base
	def to_key
		new_record? ? nil : [ self.send(self.class.primary_key) ]
	end

	def persisted?
		false
	end

	class << self
		def human_attribute_name attribute_name, options = {}
			HUMAN_ATTRIBUTE_NAMES[attribute_name.to_sym] || super
		end
	end

	HUMAN_ATTRIBUTE_NAMES = {
		:username => "Uživatel",
		:password => "Heslo"
	}
end

app/controllers/user_sessions_controller.rb
# encoding: utf-8
class UserSessionsController < ApplicationController

  # GET /user_sessions/new
  # GET /user_sessions/new.json
  def new
    @user_session = UserSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_session }
    end
  end

  # POST /user_sessions
  # POST /user_sessions.json
  def create
    @user_session = UserSession.new(params[:user_session])

    respond_to do |format|
      if @user_session.save
        format.html { redirect_to :home, notice: 'Vítej!' }
        format.json { render json: @user_session, status: :created, location: :users }
      else
        format.html { redirect_to :home }
        format.json { render json: @user_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.json
  def destroy
    @user_session = UserSession.find
    @user_session.destroy

    respond_to do |format|
      format.html { redirect_to :home, :notice => 'Měj se.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %>
	<% if @user_session.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>

			<ul>
				<% @user_session.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :username %><br />
		<%= f.text_field :username %>
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>New user_session</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>