config/routes.rb
Penezotron::Application.routes.draw do
  resources :users, :user_sessions, :transactions
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'conciliation' => 'home#conciliation', :as => :conciliation

  root :to => 'home#default', :as => :home

end

app/views/layouts/_flashes.html.erb
<% flash.each do |key,msg| %>
	<% if msg.is_a? String %>
		<div class="alert alert-<%= key == :notice ? "success" : "error" %>">
			<a class="close" data-dismiss="alert">&#215;</a>
			<%= content_tag :div, msg, :id => "flash_#{key}" %>
		</div>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Penezotron</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if current_user %>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<ul class="nav">
				<li><%= menu_icon_link current_user.username, current_user, 'user' %></li>
				<li class="divider-vertical"></li>
				<li><%= menu_icon_link "Home", :home, 'home' %></li>
				<li><%= menu_icon_link "Transakce", transactions_path, 'file' %></li>
				<li><%= menu_icon_link "Vyrovnání", :conciliation, 'retweet' %></li>
				<li><%= menu_icon_link "Změna údajů", edit_user_path(current_user.id), 'edit' %></li>
				<li><%= menu_icon_link "Registrace nového uživatele", new_user_path, 'asterisk' %></li>
			</ul>
			<ul class="nav pull-right">
				<li><%= menu_icon_link "Odhlásit", :logout, 'signout' %></li>
			</ul>
		</div>
	</div>
	<% end %>

	<div class="container">
		<div class="content">
			<%= render "layouts/flashes" %>
			<%= yield %>
		</div>
	</div>

</body>
</html>